### ISSUE TITLE
Use the build-in DRF browsable API

### ISSUE THREAD

**Issue by EwoutV** [SELab-2/UGent-7#119]
We don't really need Swagger as DRF has a built-in browsable API renderer (https://www.django-rest-framework.org/api-guide/renderers/)

```[tasklist]
### Tasks
- [ ] Enable this API renderer
- [ ] Configure the renderer so it allows users to log in. It doesn't know our authentication flow by default, so there should be a button redirecting users to CAS
- [ ] More scheme settings, such as authors, on the index
```
