### ISSUE TITLE
Add project view

### ISSUE THREAD

**Issue by DeLany123** [SELab-2/UGent-7#140]
```[tasklist]
### Tasks
- [ ] https://github.com/SELab-2/UGent-7/issues/141
- [ ] https://github.com/SELab-2/UGent-7/issues/142
- [ ] https://github.com/SELab-2/UGent-7/issues/143
- [ ] https://github.com/SELab-2/UGent-7/issues/167
- [ ] https://github.com/SELab-2/UGent-7/issues/168
- [ ] https://github.com/SELab-2/UGent-7/issues/178
- [ ] https://github.com/SELab-2/UGent-7/issues/184
- [ ] https://github.com/SELab-2/UGent-7/issues/185
- [ ] https://github.com/SELab-2/UGent-7/issues/233
- [ ] Styling project join dialog
- [ ] https://github.com/SELab-2/UGent-7/issues/239
```
