### ISSUE TITLE
cleanup services

### ISSUE THREAD

**Issue by tyboro2002** [SELab-2/UGent-7#154]
```[tasklist]
### Tasks
- [x] try making a helper class to reduce code duplication
- [ ] https://github.com/SELab-2/UGent-7/issues/149
- [x] make a user parent class
- [ ] make create always return a Response
```
