### ISSUE TITLE
Frontend: submissions

### ISSUE THREAD

**Issue by DeLany123** [SELab-2/UGent-7#187]
```[tasklist]
### Tasks
- [ ] https://github.com/SELab-2/UGent-7/issues/188
- [ ] https://github.com/SELab-2/UGent-7/issues/189
- [ ] https://github.com/SELab-2/UGent-7/issues/190
```
