### ISSUE TITLE
Frontend: make admin panel

### ISSUE THREAD

**Issue by EwoutV** [SELab-2/UGent-7#198]
We need an admin panel for general management of users and other application data.

```[tasklist]
### Tasks
- [x] Define admin layout
- [ ] Define admin routes
- [ ] Implement admin actions
```
