### ISSUE TITLE
Docs: Cleanup ER diagram

### ISSUE THREAD

**Issue by Topvennie** [SELab-2/UGent-7#224]
Cleanup the ER diagram.
```[tasklist]
### Tasks
- [x] Use the same styling (Capitalize, spaces instead of _)
- [x] Check tables if they correspond with the reality
- [x] Try to organize it as good as possible
- [x] Maybe add Types?
```
