### ISSUE TITLE
Backend: Run checks

### ISSUE THREAD

**Issue by Topvennie** [SELab-2/UGent-7#396]
```[tasklist]
### Tasks
- [x] Run extra checks after structure checks
- [x] Only give student access to logs files when they're allowed
- [x] Give teachers ability to trigger a memory or timeout limit error
- [x] Zip submissions
- [x] Figure out volume situation
- [x] Enforce memory limit and time limit
- [x] Run structure checks
- [x] Write some tests
- [x] Fixtures
- [x] Access submission files and logs
```

**Comment by Topvennie** [comment]
Enforce memory limit and time limit: [486c87f](https://github.com/SELab-2/UGent-7/pull/397/commits/486c87f0efbd9cf1afc1e463f094a7f0ad729d57)

**Comment by Topvennie** [comment]
Give teachers ability to trigger a memory or timeout limit error [05820e7](https://github.com/SELab-2/UGent-7/pull/397/commits/05820e7457954b142be666190ec722d64e6afa1a)

**Comment by Topvennie** [comment]
Run extra checks after structure checks: [cdee99f](https://github.com/SELab-2/UGent-7/pull/397/commits/cdee99f9fa99e5b257a766778198ccbb9bacc2e5)
Zip submissions: [cdee99f](https://github.com/SELab-2/UGent-7/pull/397/commits/cdee99f9fa99e5b257a766778198ccbb9bacc2e5)
Run structure checks: [cdee99f](https://github.com/SELab-2/UGent-7/pull/397/commits/cdee99f9fa99e5b257a766778198ccbb9bacc2e5)
