### ISSUE TITLE
Single Submission Page

### ISSUE THREAD

**Issue by DeLany123** [SELab-2/UGent-7#399]
```[tasklist]
### Tasks
- [x] Backend: Feedback
- [x] Route to single submission
- [x] Skelet page
- [x] Downloadable zip of files
- [x] Overview of errors
- [x] Overview of feedback
- [x] Backend: Permissions for feedback
- [x] adding feedback as teacher
- [x] editing feedback as teacher
- [ ] Color single submission when hover
- [ ] file -> bestand
- [ ] When editing submission, set focus on textfield
- [ ] After editing bug
- [ ] Make it visible when feedback is given, in the submissions overview
```
