### ISSUE TITLE
backend(notifications): a notification service for events

### ISSUE THREAD

**Issue by EwoutV** [SELab-2/UGent-7#7]
Define the events for which we should send out a notification to users. Research how we can use events in Django and if it's feasible to have a notification queue. A nice default email template in our style branding is a plus.
```[tasklist]
### Tasks
- [x] Add Events
- [x] Authentication
- [x] Hyperlink users
- [x] Send mails
- [x] Error message when creating notification with invalid user
- [ ] Tests
- [x] Type hinting
- [x] Paginating
- [x] Admins can access everyone's notifcations
- [x] Queryset ipv single
- [x] Urls naar API
- [x] Maximum 3 retries voor mails
- [x] Urls post request format
```

**Comment by EwoutV** [comment]
@Topvennie I think this can be closed since we don't have a good way to test the asynchronous nature of this module?

**Comment by Topvennie** [comment]
It's definitely possible, it's just at the bottom of the priority list for me at the moment.
